{% set name = "xsimd" %}
{% set version = "7.5.1" %}
{% set sha256 = "a865a83967161069b0eaa142818480384f82b818489f6d2187847c6ebf6d8d44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xtensor-stack/xsimd/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/xsimd/xsimd.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xsimd/xsimdConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xsimd/xsimdConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xsimd\xsimd.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xsimd\xsimdConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xsimd\xsimdConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xsimd
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ Wrappers for SIMD Intrinsices
  description: High-level APIs for SIMD operations
  doc_url: httpis://xsimd.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xsimd

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - davidbrochart
    - conda-forge/xtensor
